//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:2.0.50727.5446
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyCompany("uNhAddIns")]
[assembly: AssemblyCopyright("Copyright (c) uNhAddIns, 2008. All rights reserved.")]
[assembly: AssemblyDescription("Unofficial addins for NHibernate.")]
[assembly: AssemblyProduct("uNhAddIns")]
[assembly: AssemblyTitle("uNhAddIns")]
[assembly: CLSCompliant(true)]
[assembly: AssemblyInformationalVersion("3.0.0.773")]
[assembly: AssemblyVersion("3.0.0.773")]


